import { Inter, Lobster } from "next/font/google";
import "./globals.css";
import "../components/Navbar/Navbar.css";
import Navbar from "../components/Navbar/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Initialize only Inter and Lobster
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // adjust as needed
});

const lobster = Lobster({
  variable: "--font-lobster",
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lobster.variable} antialiased`}>
          <Navbar />
        {children}
      </body>
    </html>
  );
}
