
import { Geist, Geist_Mono, Barlow, Manrope, Lobster  } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose weights you need
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const lobster = Lobster({
  variable: "--font-lobster", // lowercase for consistency
  subsets: ["latin"],
  weight: ["400", ],
});


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
  className={`${barlow.variable} ${lobster.variable} ${manrope.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
>
  {children}
</body>

    </html>
  );
}
